sudo: false

env:
  global:
    - COVERITY_SCAN_TOKEN: 4YeBZh3O0qD3S3Y75qjkLQ
#    - secure: "g/CtgvbfdLNOvXnAMCHxv0HDafDyjl8YJX+cym8Gni8fjcBOsbhgIJzap0yDnT8K8YrKmZvlLn53ROJq+UYBHzw+gura6y5YHouxCq3zJqCH47v+0R8BLchXd3XqQ2fqHoqg6xkX/R7fiTWXGBdtLrO4det6RqYtPNeFovqQP4U="

addons:
  apt:
    packages:
      - valgrind
  coverity_scan:
    project:
      name: CppMicroServices/CppMicroServices
      description: "Build submitted via Travis CI"
    notification_email: sascha.zelzer@gmail.com
    build_command_prepend: "mkdir us-cov; cd us-cov; cmake -DCMAKE_BUILD_TYPE:STRING=Release -DUS_BUILD_EXAMPLES:BOOL=ON -DUS_BUILD_TESTING:BOOL=ON -DUS_BUILD_SHARED_LIBS:BOOL=ON ../"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

cache:
  directories:
    - $HOME/cache

language: cpp
compiler:
  - gcc
#  - clang

env:
  global:
  - PATH=$HOME/cache/bin/:$PATH
  matrix:
  - BUILD_CONFIGURATION=0
  - BUILD_CONFIGURATION=1
  #- BUILD_CONFIGURATION=2
  #- BUILD_CONFIGURATION=3

branches:
  except:
    - gh_pages

before_install:
  - test $TRAVIS_BRANCH != coverity_scan -o ${TRAVIS_JOB_NUMBER##*.} = 1 || exit 0
  - bash install_cmake.sh

script:
  - test $TRAVIS_BRANCH != coverity_scan || exit 0
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ctest -VV -S ./cmake/usCTestScript_travis.cmake ; fi

